### ISSUE TITLE
How to use conditionals?

### ISSUE THREAD

**Issue by jacksondus** [roscopeco/deelang#13]
In short, I need to do something like this:

<code>if(game.hasGlobalFlag("how_to_do_this"){game.removeGlobalFlag("how_to_do_this")}</code>

I am not sure how I would go about doing something like this in Deelang.

**Comment by roscopeco** [comment]
There is no conditional support in the language. The intention is that you have something like this on your `self` object:

```java
public void test(Block block, Boolean bool) {
  if (bool) block.invoke;
  else getBinding().setErrorFlag();
}
```

which would allow you to then do (in Dee):

```java
test(game.hasGlobalFlag("how_to_do_this")) {
  game.removeGlobalFlag("how_to_do_this"));
}
```

And supports the 'or' construct, e.g.

```java 
test(game.hasGlobalFlag("how_to_do_this")) {
  game.removeGlobalFlag("how_to_do_this"));
} or {
  game.addGlobalFlag("how_to_do_this"));
}
```

**Comment by jacksondus** [comment]
@roscopeco So the 'or' construct would be called by 'getBinding().setErrorFlag()'... Still considering the suitability for this in my project, along with several other languages. Is it possible to create new variables for things such as booleans and other primitives, or is it expected that all referenced variables are declared in Java?
